### ISSUE TITLE
Bounty Board Claim button not correctly linking to the create bounty

### ISSUE THREAD

**Issue by Icedcool** [BanklessDAO/bounty-board#85]
**Describe the bug**
Clicking the claim button on a bounty directs you to http://https://bountyboard.bankless.community/

**To Reproduce**
http://https://bountyboard.bankless.community/
Click an open bounty
The claim link is populated as: https://bountyboard.bankless.community/
Clicking takes you to the top of the page.

**Expected behavior**
Click 'Claim' and takes you to the bounty.

**Screenshots**
https://app.usebubbles.com/4juX64EwSMSBMVtaaKTXNH/bankless-dao-bounty-board-bug-report-can-t-claim-task

**Comment by Oktalize** [comment]
@Behold3th are you able to take a look at this one?

**Comment by Behold3th** [comment]
> @Behold3th are you able to take a look at this one?

can do!

**Comment by Behold3th** [comment]
Picking this one up. To give context this was an intentional choice as we wanted users to claim bounties on the Discord, as front-end claiming is only unblocked by oauth2 integration. There are a few solutions - remove the claim button and leave a helpful message such as "Claim on the discord" - or have the button deep link to the posted bounty. The second option is preferred and what I will implement

**Comment by jordaniza** [comment]
@Behold3th can you confirm if this is sorted please?

**Comment by Behold3th** [comment]
Yes, this has been sorted
